# Generated by Django 4.1 on 2023-06-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
    ]
