# Generated by Django 4.1 on 2023-06-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
