# Generated by Django 4.2.3 on 2023-08-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
