# Generated by Django 4.2.4 on 2023-09-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_book_book_available_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Ordered',
            new_name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
